/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/mediums/medium-toobar-second copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    FixedPage: typeof import('./src/components/FixedPage.vue')['default']
    LibraryScanButton: typeof import('./src/components/headers/library-scan-button.vue')['default']
    LibraryTitleComponent: typeof import('./src/components/sider-menus/library-title-component.vue')['default']
    MainLibraryTitleComponent: typeof import('./src/components/sider-menus/main-library-title-component.vue')['default']
    MediumContent: typeof import('./src/components/mediums/medium-content.vue')['default']
    MediumGuidItem: typeof import('./src/components/mediums/medium-guid-item.vue')['default']
    MediumLayoutDropdownSelect: typeof import('./src/components/mediums/medium-layout-dropdown-select.vue')['default']
    MediumListItem: typeof import('./src/components/mediums/medium-list-item.vue')['default']
    MediumRecommendation: typeof import('./src/components/mediums/medium-recommendation.vue')['default']
    MediumRecommendationSection: typeof import('./src/components/mediums/medium-recommendation-section.vue')['default']
    MediumRecommendationSectionExample: typeof import('./src/components/mediums/medium-recommendation-section-example.vue')['default']
    MediumRecommendGroup: typeof import('./src/components/mediums/medium-recommend-group.vue')['default']
    MediumSortDropdown: typeof import('./src/components/mediums/medium-sort-dropdown.vue')['default']
    MediumToolbar: typeof import('./src/components/mediums/medium-toolbar.vue')['default']
    MediumToolbarFirst: typeof import('./src/components/mediums/medium-toolbar-first.vue')['default']
    MediumToolbarSecond: typeof import('./src/components/mediums/medium-toolbar-second.vue')['default']
    MediumToolbarSecondSelect: typeof import('./src/components/mediums/medium-toolbar-second-select.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
